# Generated by Django 3.2 on 2021-06-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='orderItem',
            field=models.ManyToManyField(to='store.OrderItem'),
        ),
    ]
