# Generated by Django 3.2 on 2021-06-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210617_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Picked', 'Picked'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
