# Generated by Django 3.2 on 2021-06-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210617_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Picked', 'Picked'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled')], default='Pending', max_length=200, null=True),
        ),
    ]
